version: '3'
services:
  trudesk:
    image: polonel/trudesk
    restart: always
    ports:
      - "8118:8118"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
  mongo:
    image: mongo:3.6.14-xenial
    restart: always
    ports:
      - "26017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
